In [1]:
#from google.colab import drive
#drive.mount('/content/drive')

In [68]:
import pandas as pd


In [69]:

# import os, types
# import pandas as pd
# from botocore.client import Config
# import ibm_boto3

# def __iter__(self): return 0

# # @hidden_cell
# # The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# # You might want to remove those credentials before you share the notebook.

# if os.environ.get('RUNTIME_ENV_LOCATION_TYPE') == 'external':
#     endpoint_7c4d6a67af124d53ba9c5f80de0fab40 = 'https://s3.eu.cloud-object-storage.appdomain.cloud'
# else:
#     endpoint_7c4d6a67af124d53ba9c5f80de0fab40 = 'https://s3.eu.cloud-object-storage.appdomain.cloud'

# client_7c4d6a67af124d53ba9c5f80de0fab40 = ibm_boto3.client(service_name='s3',
#     ibm_api_key_id='hNlRerQd6g4PT94rIEY3SzDgq_2nvOujh3OMJGPo91sf',
#     ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
#     config=Config(signature_version='oauth'),
#     endpoint_url=endpoint_7c4d6a67af124d53ba9c5f80de0fab40)

# body = client_7c4d6a67af124d53ba9c5f80de0fab40.get_object(Bucket='greenifymultioutputtreesandgrassa-donotdelete-pr-k0ecjydqyomgnp',Key='Trees.csv')['Body']
# # add missing __iter__ method, so pandas accepts body as file-like object
# if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

# df= pd.read_csv(body)
# df.head()


In [70]:
#df.head()

In [71]:
#df_new=df.drop(columns=['Unnamed: 0','Unnamed: 1','Unnamed: 7','Unnamed: 8'])

In [72]:
#df_new.head()

In [73]:
#df_new=df_new.drop(columns=['Very Dense Forest','Mod.\nDense\nForest','Open Forest','Scrub'])

In [74]:
#df_new.head()

In [77]:
#df_final=df_new[['Geographical Area (GA)','Total','Total population','Total Carbon Dioxide in State','No. of trees that can be planted (21kg = 1 tree)','Grass Land Area in KM^2 (1000m^2=1/44 tons of CO2)
body = client_7c4d6a67af124d53ba9c5f80de0fab40.get_object(Bucket='greenifymultioutputtreesandgrassa-donotdelete-pr-k0ecjydqyomgnp',Key='finalTrees.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_final_1 = pd.read_csv(body)
df_final.head()


Geographical Area (GA)    Total  Total population  \
0                  1841.0  1406.17           36842.0   
1                  3736.0  3070.53          105597.0   
2                  2672.0  2266.08          238142.0   
3                  8249.0  6742.78          380581.0   
4                 16105.0  5721.32         2741239.0   

   Total Carbon Dioxide in State  \
0                   0.000000e+00   
1                   0.000000e+00   
2                   0.000000e+00   
3                   0.000000e+00   
4                   4.415803e+09   

   No. of trees that can be planted (21kg = 1 tree)  \
0                                      0.000000e+00   
1                                      0.000000e+00   
2                                      0.000000e+00   
3                                      0.000000e+00   
4                                      2.102764e+08   

   Grass Land Area in KM^2 (1000m^2=1/44 tons of CO2)  
0                                               0.00   
1                                               0.00   
2                                               0.00   
3                                               0.00   
4                                            1204.31

In [78]:

df_final[df_final<0]=0
df_final.head()

Geographical Area (GA)    Total  Total population  \
0                  1841.0  1406.17           36842.0   
1                  3736.0  3070.53          105597.0   
2                  2672.0  2266.08          238142.0   
3                  8249.0  6742.78          380581.0   
4                 16105.0  5721.32         2741239.0   

   Total Carbon Dioxide in State  \
0                   0.000000e+00   
1                   0.000000e+00   
2                   0.000000e+00   
3                   0.000000e+00   
4                   4.415803e+09   

   No. of trees that can be planted (21kg = 1 tree)  \
0                                      0.000000e+00   
1                                      0.000000e+00   
2                                      0.000000e+00   
3                                      0.000000e+00   
4                                      2.102764e+08   

   Grass Land Area in KM^2 (1000m^2=1/44 tons of CO2)  
0                                               0.00   
1                                               0.00   
2                                               0.00   
3                                               0.00   
4                                            1204.31

In [79]:
df_final.tail()

Geographical Area (GA)     Total  Total population  \
661                  4713.0    820.05         5095875.0   
662                  6259.0    915.88         2930115.0   
663                  9960.0   2788.71         8161961.0   
664                  3140.0    234.93         3007134.0   
665                 88752.0  16901.51        91276115.0   

     Total Carbon Dioxide in State  \
661                   1.265969e+10   
662                   7.020303e+09   
663                   1.941694e+10   
664                   7.615752e+09   
665                   2.254676e+11   

     No. of trees that can be planted (21kg = 1 tree)  \
661                                      6.028425e+08   
662                                      3.343002e+08   
663                                      9.246161e+08   
664                                      3.626548e+08   
665                                      1.073655e+10   

     Grass Land Area in KM^2 (1000m^2=1/44 tons of CO2)  
661                                            3452.64   
662                                            1914.63   
663                                            5295.53   
664                                            2077.02   
665                                           61491.17

In [80]:
#df_final['Total'].replace(np.nan,16901.51,inplace=True)

In [81]:
df_final.shape

(664, 6)

In [82]:
df_final.isnull().sum().sum()

0

In [83]:
df_final=df_final.dropna()

In [84]:
X=df_final.iloc[:,:-2].values

In [85]:
Y=df_final.iloc[:,-2:].values

In [86]:
X.shape

(664, 4)

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)

In [89]:
X_train.shape

(531, 4)

In [90]:
X.shape

(664, 4)

In [91]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [92]:
X_train.shape

(531, 4)

In [93]:
X_test.shape

(133, 4)

In [94]:
Y_train = sc.fit_transform(y_train)
Y_test = sc.transform(y_test)

In [95]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge
clf = MultiOutputRegressor(Ridge(random_state=123)).fit(X_train, Y_train)
y_pred=clf.predict(X_test)

In [96]:
y_pred.shape

(133, 2)

In [97]:
import matplotlib.pyplot as plt

In [98]:
from sklearn.metrics import accuracy_score

In [99]:
from sklearn.metrics import explained_variance_score
explained_variance_score(Y_test, y_pred)

0.9999549977541673

In [134]:
import numpy as np
def predict(x):
    #x=sc.transform(x)
    a1=np.array(x)
    x1=a1.reshape(1,-1)
    y1=clf.predict(x1)
    print("No of Trees Required and Grassland Required respectively: ",y1[0])
    #print("Area of GrassLand: ",y1[1],"(in km^2)")

In [135]:
predict([1841.0,1406.17,36842.0,0.0])

No of Trees Required and Grassland Required respectively:  [1427.73631729 1427.7329766 ]


In [100]:
Y_test[-1]

array([-0.17309741, -0.17309691])

In [101]:
y_pred[-1]

array([-0.1725072 , -0.17250719])

In [102]:
Y_test[8]

array([0.08411798, 0.08411765])

In [103]:
y_pred[8]

array([0.08119488, 0.08119488])

In [104]:
from sklearn.metrics import mean_squared_error
mean_squared_error(Y_test, y_pred, squared=False)

0.0025269358118728434

In [105]:
#df_final.to_csv(r'/content/drive/MyDrive/Final_Trees/finalTrees.csv', index=False)

In [106]:
#pip install ibm_watson_machine_learning

In [107]:
from ibm_watson_machine_learning import APIClient
wml_credentials={
    "url":"https://eu-gb.ml.cloud.ibm.com",
    "apikey":"tU4GkB7cfqrwUlvd-akBxGoRkIF5zqdjY4nu3oLt7C6O"
}
client=APIClient(wml_credentials)

In [108]:
def guid_from_space_name(client,space_name):
    space=client.spaces.get_details()
    return(next(item for item in space['resources'] if item['entity']['name']==space_name)['metadata']['id'])

In [109]:
space_uid=guid_from_space_name(client,'models')
print("Space UID= "+space_uid)

Space UID= 8ae57b0b-5dc1-452f-b126-657866c45286


In [110]:
client.set.default_space(space_uid)

'SUCCESS'

In [111]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
scikit-learn_0.22-py3.6        154010fa-5b3b-4ac1-82af-4d5ee5abbc85  base
default_r3.6                   1b70aec3-ab34-4b87-8aa0-a4a3c8296a36  base
pytorch-onnx_1.3-py3.6         1bc6029a-cc97-56da-b8e0-39c3880dbbe7  base
tensorflow_2.1-py3.6           1eb25b8

In [112]:
software_spec_uid=client.software_specifications.get_uid_by_name("default_py3.7")
software_spec_uid

'e4429883-c883-42b6-87a8-f419d64088cd'

In [113]:
model_details=client.repository.store_model(model=clf,meta_props={
    client.repository.ModelMetaNames.NAME:"Greenify-MultiOutput-Trees and Grass Area Prediction",
    client.repository.ModelMetaNames.TYPE:"scikit-learn_0.23",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_spec_uid}
                                          
    )
model_id=client.repository.get_model_uid(model_details)

In [114]:
model_id

'0487d7bf-5ff9-4deb-a165-a0a33f5c1354'

In [115]:
x=X_train[0]

In [116]:
x


array([-0.21123979, -0.06688937, -0.142206  , -0.17573832])

In [117]:
x0=x.reshape(1,-1)

In [118]:
clf.predict(x0)

array([[-0.17474538, -0.17474539]])

In [120]:
Y_train[0]

array([-0.17573832, -0.17573782])